name: Merged PR

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

jobs:
  notify:
    # マージされた場合
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PR_URL: ${{ github.event.pull_request.url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          USER_NAME: ${{ github.triggering_actor }}
        run: |
          set -e
          CONTENT="✅ プルリクエストがマージされました。\n  リンク: [$PR_TITLE]($PR_URL) \n  実施者: $USER_NAME"
          curl -H "Content-Type: application/json" \
               -d "{\"content\":\"${CONTENT}\"}" \
               "$DISCORD_WEBHOOK_URL"
